# Data Preprocessing Tools

## Importing the libraries

In [59]:
# 30/11/2023
# IDE: VSC
# Sección 3: Data Preprocessing in Python 
# Preprocessing counts for 70% of the work of a data scientist

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [60]:
# Videos [11, 16]
dataset = pd.read_csv("Data.csv")

# we use the feature matrix to predict the dependant variable (last column)
# features: country, age, salary
# dependant variable: purchased

# X = feature matrix
# iloc --> index location (columns or rows)
# [:, :-1] --> [take all the rows, take all the columns minus the last one]
X = dataset.iloc[:, :-1].values

# Y = dependant variable vector
# [:, -1] --> [take all the rows, take the last column]
y = dataset.iloc[:, -1].values

In [61]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [62]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [63]:
# Videos [18, 19]
# chatGPT: see how many nan values are there 

# Xbis --> Leaving only numeric values
Xbis = dataset.iloc[:, 1:-1].astype(float)

# Loop through each column 
for col_name in Xbis.columns:
    
    # Check if any value in the column is np.nan
    if Xbis[col_name].isnull().any():

        # Count the total number of values in the column
        total_values = Xbis[col_name].size
        
        # Count the number of np.nan values in the column
        nan_sum = Xbis[col_name].isnull().sum()
        
        # Calculate the percentage of np.nan values
        nan_percentage = (nan_sum / total_values) * 100
        print(f"Column {col_name}:")
        print(f"\t-> Sum of np.nan values = {nan_sum}/{total_values}")
        print(f"\t-> Percentage = {nan_percentage}%")

Column Age:
	-> Sum of np.nan values = 1/10
	-> Percentage = 10.0%
Column Salary:
	-> Sum of np.nan values = 1/10
	-> Percentage = 10.0%


In [64]:
# Videos [18, 19]
from sklearn.impute import SimpleImputer

# replace the nan values my the mean
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

# de las columna [1,2] reemplazame, transform, los nan en mean
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [65]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [66]:
# Videos [20, 22]
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# transformers=[('encoder', ... )] --> encoding transformation
# transformers=[ ... , OneHotEncoder() --> class that will do the transformation
# transformers=[ ..., [0]) ] --> column where you want to apply the encoding
# remainder='passthrough' --> if you do not include this parameter, you don't get the !country columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# it is absolutely compulsory to have X as a numpy array, this will be expected by the future ML models
X = np.array(ct.fit_transform(X))

In [67]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [68]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Transform the yesses and noes into 1's and 0's
y = le.fit_transform(y)

In [69]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [70]:
# Videos [23, 25]
from sklearn.model_selection import train_test_split

# test_size: recommended size of the split
# --> 80% observation on the training set (8 customers go on the training set)
# --> 20% in the test set (2 customers go in the test set)
# random_state: fixing the seed so that we get the same split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [71]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [72]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [73]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [74]:
print(y_test)

[0 1]


## Feature Scaling

In [75]:
# 1/12/2023
# Videos [26, 29]

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# fit_transform for all the variables that are not dummy variables in X_train
# fit: will get the mean and standard deviation of each feature
# transform: applies the standardization formula so that all values can be in the same scale
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# The features of the test set need to be scaled by the same scaler that was used on the training set
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [76]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [77]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
