# Artificial Neural Network

### Importing the libraries

In [34]:
# 10/01/2024
# IDE: VSC
# EXTRA (BONUS): Artificial Neural Networks for Regression
# 345. EXTRA CONTENT: ANN Case Study

# pip install tensorflow==2.14.0


import numpy as np
import pandas as pd
import tensorflow as tf

In [35]:
tf.__version__

'2.14.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [36]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')


# Features (X) consist of hourly average ambient variables:
# Temperature (AT)
# Exhaust Vacuum (V)
# Ambient Pressure (AP)
# Relative Humidity (RH) 
X = dataset.iloc[:, :-1].values

# Predict (y) the net hourly electrical energy output (PE) of the plant:
y = dataset.iloc[:, -1].values

In [47]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [48]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [37]:
# Origin: data_preprocessing_tools

from sklearn.model_selection import train_test_split

# test_size: recommended size of the split
# --> 80% observation on the training set 
# --> 20% in the test set
# random_state: fixing the seed so that we get the same split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [38]:
# ANN (Artificial Neural Network)
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [39]:
# units=6 --> 6 neurons (Hyperparameter)
# activation='relu' --> re_ctifier l_inear u_nit --> rectifier activation function

# activation function:
# sigmoid: yes or no, 0 or 1
# softmax: classification with >2 categories or classes to predict
# no activation function: regression, continuous real number

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [40]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [41]:
# units=1 --> only 1 output neuron is needed to encode a binary outcome
# no activation function in the output layer
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [42]:
# the best optimizers are the ones that can perform gradient descent
# stochastic gradient descent: it updates the weights to reduce the loss error between predictions and results

# non-binary loss function--> loss= 'categorical_crossentropy'
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [43]:
# batch_size --> we do the comparison of trainning vs test in batches instead of 1vs1
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50


240/240 [==============================] - 1s 1ms/step - loss: 207568.4844
Epoch 2/50
240/240 [==============================] - 0s 1ms/step - loss: 4188.6855
Epoch 3/50
240/240 [==============================] - 0s 1ms/step - loss: 166.5903
Epoch 4/50
240/240 [==============================] - 0s 1ms/step - loss: 164.5221
Epoch 5/50
240/240 [==============================] - 0s 1ms/step - loss: 162.5028
Epoch 6/50
240/240 [==============================] - 0s 1ms/step - loss: 160.1256
Epoch 7/50
240/240 [==============================] - 0s 1ms/step - loss: 157.2835
Epoch 8/50
240/240 [==============================] - 0s 1ms/step - loss: 154.1474
Epoch 9/50
240/240 [==============================] - 0s 1ms/step - loss: 150.5482
Epoch 10/50
240/240 [==============================] - 0s 1ms/step - loss: 146.7991
Epoch 11/50
240/240 [==============================] - 0s 1ms/step - loss: 142.2731
Epoch 12/50
240/240 [==============================] - 0s 1ms/step - loss: 137.5066
Epoch 13

### Predicting the results of the Test set

In [44]:
y_pred = ann.predict(X_test)
# precision = 2 --> 2 decimals
np.set_printoptions(precision=2)

# reshape(len(y_pred),1) --> display vertically
# axis can take 2 values (0, 1)
# --> 0: horizontal concatenation
# --> 1: vertical concatenation

# print(np.concatenate((y_pred, y_test), 0))
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

# Left column (prediction) | Right column (test)

60/60 [==============================] - 0s 886us/step
[[428.4  431.23]
 [461.51 460.01]
 [466.1  461.14]
 ...
 [471.26 473.26]
 [441.71 438.  ]
 [459.41 463.28]]


### Making the Confusion Matrix

In [ ]:
# you can't make the confusion matrix for continuous values